# Generated by Django 4.0.5 on 2022-07-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputToOutputDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.PositiveSmallIntegerField()),
                ('gov_id', models.PositiveSmallIntegerField()),
                ('output', models.JSONField()),
            ],
        ),
    ]
