# Generated by Django 4.0.5 on 2022-07-14 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtooutputdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputtooutputdocument',
            name='progress',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
