# Generated by Django 4.0.5 on 2022-07-14 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_filterbyvalueinonecol'),
        ('techniques', '0002_inputtooutputdocument_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtooutputdocument',
            name='month',
            field=models.ForeignKey(default=255, on_delete=django.db.models.deletion.PROTECT, to='base.month'),
            preserve_default=False,
        ),
    ]
