# Generated by Django 4.0.5 on 2022-07-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0003_inputtooutputdocument_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtooutputdocument',
            name='output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
