# Generated by Django 4.0.5 on 2022-07-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0004_alter_inputtooutputdocument_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtooutputdocument',
            name='sample_selection_kwargs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
