# Generated by Django 4.0.5 on 2022-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0005_inputtooutputdocument_sample_selection_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtooutputdocument',
            name='sample_selection_kwargs',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
