# Generated by Django 4.0.5 on 2022-07-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0006_alter_inputtooutputdocument_sample_selection_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtooutputdocument',
            name='sample_selection_kwargs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
