PROVINCIAL_CAPITALS_NAMES = [
    "哈尔滨",
    "长春",
    "沈阳",
    "石家庄",
    "兰州",
    "西宁",
    "西安",
    "郑州",
    "济南",
    "太原",
    "合肥",
    "武汉",
    "长沙",
    "南京",
    "成都",
    "贵阳",
    "昆明",
    "杭州",
    "南昌",
    "广州",
    "福州",
    "海口",
    "乌鲁木齐",
    "呼和浩特",
    "银川",
    "南宁",
    "拉萨",
    "北京",
    "上海",
    "天津",
    "重庆",
    "香港",
    "澳门",
    "台北",
]


PROVINCIAL_CAPITALS_CHILDREN = [
    {
        "gov_id": 2,
        "name": "东城区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 3,
        "name": "西城区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 4,
        "name": "朝阳区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 5,
        "name": "丰台区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 6,
        "name": "石景山区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 7,
        "name": "海淀区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 8,
        "name": "门头沟区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 9,
        "name": "房山区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 10,
        "name": "通州区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 11,
        "name": "顺义区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 12,
        "name": "昌平区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 13,
        "name": "大兴区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 14,
        "name": "怀柔区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 15,
        "name": "平谷区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 16,
        "name": "密云区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 17,
        "name": "延庆区",
        "children": [],
        "parent_id": 1,
        "parent_name": "北京市",
    },
    {
        "gov_id": 19,
        "name": "和平区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 20,
        "name": "河东区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 21,
        "name": "河西区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 22,
        "name": "南开区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 23,
        "name": "河北区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 24,
        "name": "红桥区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 25,
        "name": "东丽区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 26,
        "name": "西青区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 27,
        "name": "津南区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 28,
        "name": "北辰区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 29,
        "name": "武清区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 30,
        "name": "宝坻区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 31,
        "name": "滨海新区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 32,
        "name": "宁河区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 33,
        "name": "静海区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 34,
        "name": "蓟州区",
        "children": [],
        "parent_id": 18,
        "parent_name": "天津市",
    },
    {
        "gov_id": 37,
        "name": "长安区",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 38,
        "name": "桥西区",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 39,
        "name": "新华区",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 40,
        "name": "井陉矿区",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 41,
        "name": "裕华区",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 42,
        "name": "藁城区",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 43,
        "name": "鹿泉区",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 44,
        "name": "栾城区",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 45,
        "name": "井陉县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 46,
        "name": "正定县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 47,
        "name": "行唐县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 48,
        "name": "灵寿县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 49,
        "name": "高邑县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 50,
        "name": "深泽县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 51,
        "name": "赞皇县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 52,
        "name": "无极县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 53,
        "name": "平山县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 54,
        "name": "元氏县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 55,
        "name": "赵县",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 56,
        "name": "辛集市",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 57,
        "name": "晋州市",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 58,
        "name": "新乐市",
        "children": [],
        "parent_id": 36,
        "parent_name": "石家庄市",
    },
    {
        "gov_id": 220,
        "name": "小店区",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 221,
        "name": "迎泽区",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 222,
        "name": "杏花岭区",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 223,
        "name": "尖草坪区",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 224,
        "name": "万柏林区",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 225,
        "name": "晋源区",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 226,
        "name": "清徐县",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 227,
        "name": "阳曲县",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 228,
        "name": "娄烦县",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 229,
        "name": "古交市",
        "children": [],
        "parent_id": 219,
        "parent_name": "太原市",
    },
    {
        "gov_id": 351,
        "name": "新城区",
        "children": [],
        "parent_id": 350,
        "parent_name": "呼和浩特市",
    },
    {
        "gov_id": 352,
        "name": "回民区",
        "children": [],
        "parent_id": 350,
        "parent_name": "呼和浩特市",
    },
    {
        "gov_id": 353,
        "name": "玉泉区",
        "children": [],
        "parent_id": 350,
        "parent_name": "呼和浩特市",
    },
    {
        "gov_id": 354,
        "name": "赛罕区",
        "children": [],
        "parent_id": 350,
        "parent_name": "呼和浩特市",
    },
    {
        "gov_id": 355,
        "name": "土默特左旗",
        "children": [],
        "parent_id": 350,
        "parent_name": "呼和浩特市",
    },
    {
        "gov_id": 356,
        "name": "托克托县",
        "children": [],
        "parent_id": 350,
        "parent_name": "呼和浩特市",
    },
    {
        "gov_id": 357,
        "name": "和林格尔县",
        "children": [],
        "parent_id": 350,
        "parent_name": "呼和浩特市",
    },
    {
        "gov_id": 358,
        "name": "清水河县",
        "children": [],
        "parent_id": 350,
        "parent_name": "呼和浩特市",
    },
    {
        "gov_id": 359,
        "name": "武川县",
        "children": [],
        "parent_id": 350,
        "parent_name": "呼和浩特市",
    },
    {
        "gov_id": 466,
        "name": "和平区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 467,
        "name": "沈河区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 468,
        "name": "大东区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 469,
        "name": "皇姑区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 470,
        "name": "铁西区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 471,
        "name": "苏家屯区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 472,
        "name": "浑南区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 473,
        "name": "沈北新区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 474,
        "name": "于洪区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 475,
        "name": "辽中区",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 476,
        "name": "康平县",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 477,
        "name": "法库县",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 478,
        "name": "新民市",
        "children": [],
        "parent_id": 465,
        "parent_name": "沈阳市",
    },
    {
        "gov_id": 581,
        "name": "南关区",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 582,
        "name": "宽城区",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 583,
        "name": "朝阳区",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 584,
        "name": "二道区",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 585,
        "name": "绿园区",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 586,
        "name": "双阳区",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 587,
        "name": "九台区",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 588,
        "name": "农安县",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 589,
        "name": "榆树市",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 590,
        "name": "德惠市",
        "children": [],
        "parent_id": 580,
        "parent_name": "长春市",
    },
    {
        "gov_id": 651,
        "name": "道里区",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 652,
        "name": "南岗区",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 653,
        "name": "道外区",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 654,
        "name": "平房区",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 655,
        "name": "松北区",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 656,
        "name": "香坊区",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 657,
        "name": "呼兰区",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 658,
        "name": "阿城区",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 659,
        "name": "双城区",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 660,
        "name": "依兰县",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 661,
        "name": "方正县",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 662,
        "name": "宾县",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 663,
        "name": "巴彦县",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 664,
        "name": "木兰县",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 665,
        "name": "通河县",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 666,
        "name": "延寿县",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 667,
        "name": "尚志市",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 668,
        "name": "五常市",
        "children": [],
        "parent_id": 650,
        "parent_name": "哈尔滨市",
    },
    {
        "gov_id": 792,
        "name": "黄浦区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 793,
        "name": "徐汇区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 794,
        "name": "长宁区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 795,
        "name": "静安区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 796,
        "name": "普陀区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 797,
        "name": "虹口区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 798,
        "name": "杨浦区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 799,
        "name": "闵行区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 800,
        "name": "宝山区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 801,
        "name": "嘉定区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 802,
        "name": "浦东新区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 803,
        "name": "金山区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 804,
        "name": "松江区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 805,
        "name": "青浦区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 806,
        "name": "奉贤区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 807,
        "name": "崇明区",
        "children": [],
        "parent_id": 791,
        "parent_name": "上海市",
    },
    {
        "gov_id": 810,
        "name": "玄武区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 811,
        "name": "秦淮区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 812,
        "name": "建邺区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 813,
        "name": "鼓楼区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 814,
        "name": "浦口区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 815,
        "name": "栖霞区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 816,
        "name": "雨花台区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 817,
        "name": "江宁区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 818,
        "name": "六合区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 819,
        "name": "溧水区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 820,
        "name": "高淳区",
        "children": [],
        "parent_id": 809,
        "parent_name": "南京市",
    },
    {
        "gov_id": 921,
        "name": "上城区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 922,
        "name": "下城区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 923,
        "name": "江干区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 924,
        "name": "拱墅区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 925,
        "name": "西湖区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 926,
        "name": "滨江区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 927,
        "name": "萧山区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 928,
        "name": "余杭区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 929,
        "name": "富阳区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 930,
        "name": "桐庐县",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 931,
        "name": "淳安县",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 932,
        "name": "建德市",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 933,
        "name": "临安区",
        "children": [],
        "parent_id": 920,
        "parent_name": "杭州市",
    },
    {
        "gov_id": 1023,
        "name": "瑶海区",
        "children": [],
        "parent_id": 1022,
        "parent_name": "合肥市",
    },
    {
        "gov_id": 1024,
        "name": "庐阳区",
        "children": [],
        "parent_id": 1022,
        "parent_name": "合肥市",
    },
    {
        "gov_id": 1025,
        "name": "蜀山区",
        "children": [],
        "parent_id": 1022,
        "parent_name": "合肥市",
    },
    {
        "gov_id": 1026,
        "name": "包河区",
        "children": [],
        "parent_id": 1022,
        "parent_name": "合肥市",
    },
    {
        "gov_id": 1027,
        "name": "长丰县",
        "children": [],
        "parent_id": 1022,
        "parent_name": "合肥市",
    },
    {
        "gov_id": 1028,
        "name": "肥东县",
        "children": [],
        "parent_id": 1022,
        "parent_name": "合肥市",
    },
    {
        "gov_id": 1029,
        "name": "肥西县",
        "children": [],
        "parent_id": 1022,
        "parent_name": "合肥市",
    },
    {
        "gov_id": 1030,
        "name": "庐江县",
        "children": [],
        "parent_id": 1022,
        "parent_name": "合肥市",
    },
    {
        "gov_id": 1031,
        "name": "巢湖市",
        "children": [],
        "parent_id": 1022,
        "parent_name": "合肥市",
    },
    {
        "gov_id": 1145,
        "name": "鼓楼区",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1146,
        "name": "台江区",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1147,
        "name": "仓山区",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1148,
        "name": "马尾区",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1149,
        "name": "晋安区",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1150,
        "name": "闽侯县",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1151,
        "name": "连江县",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1152,
        "name": "罗源县",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1153,
        "name": "闽清县",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1154,
        "name": "永泰县",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1155,
        "name": "平潭县",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1156,
        "name": "福清市",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1157,
        "name": "长乐区",
        "children": [],
        "parent_id": 1144,
        "parent_name": "福州市",
    },
    {
        "gov_id": 1240,
        "name": "东湖区",
        "children": [],
        "parent_id": 1239,
        "parent_name": "南昌市",
    },
    {
        "gov_id": 1241,
        "name": "西湖区",
        "children": [],
        "parent_id": 1239,
        "parent_name": "南昌市",
    },
    {
        "gov_id": 1242,
        "name": "青云谱区",
        "children": [],
        "parent_id": 1239,
        "parent_name": "南昌市",
    },
    {
        "gov_id": 1243,
        "name": "湾里区",
        "children": [],
        "parent_id": 1239,
        "parent_name": "南昌市",
    },
    {
        "gov_id": 1244,
        "name": "青山湖区",
        "children": [],
        "parent_id": 1239,
        "parent_name": "南昌市",
    },
    {
        "gov_id": 1245,
        "name": "新建区",
        "children": [],
        "parent_id": 1239,
        "parent_name": "南昌市",
    },
    {
        "gov_id": 1246,
        "name": "南昌县",
        "children": [],
        "parent_id": 1239,
        "parent_name": "南昌市",
    },
    {
        "gov_id": 1247,
        "name": "安义县",
        "children": [],
        "parent_id": 1239,
        "parent_name": "南昌市",
    },
    {
        "gov_id": 1248,
        "name": "进贤县",
        "children": [],
        "parent_id": 1239,
        "parent_name": "南昌市",
    },
    {
        "gov_id": 1352,
        "name": "历下区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1353,
        "name": "市中区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1354,
        "name": "槐荫区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1355,
        "name": "天桥区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1356,
        "name": "历城区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1357,
        "name": "长清区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1358,
        "name": "平阴县",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1359,
        "name": "济阳区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1360,
        "name": "商河县",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1361,
        "name": "章丘区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1451,
        "name": "莱芜区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1452,
        "name": "钢城区",
        "children": [],
        "parent_id": 1351,
        "parent_name": "济南市",
    },
    {
        "gov_id": 1507,
        "name": "中原区",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1508,
        "name": "二七区",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1509,
        "name": "管城回族区",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1510,
        "name": "金水区",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1511,
        "name": "上街区",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1512,
        "name": "惠济区",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1513,
        "name": "中牟县",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1514,
        "name": "巩义市",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1515,
        "name": "荥阳市",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1516,
        "name": "新密市",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1517,
        "name": "新郑市",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1518,
        "name": "登封市",
        "children": [],
        "parent_id": 1506,
        "parent_name": "郑州市",
    },
    {
        "gov_id": 1683,
        "name": "江岸区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1684,
        "name": "江汉区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1685,
        "name": "硚口区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1686,
        "name": "汉阳区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1687,
        "name": "武昌区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1688,
        "name": "青山区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1689,
        "name": "洪山区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1690,
        "name": "东西湖区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1691,
        "name": "汉南区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1692,
        "name": "蔡甸区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1693,
        "name": "江夏区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1694,
        "name": "黄陂区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1695,
        "name": "新洲区",
        "children": [],
        "parent_id": 1682,
        "parent_name": "武汉市",
    },
    {
        "gov_id": 1800,
        "name": "芙蓉区",
        "children": [],
        "parent_id": 1799,
        "parent_name": "长沙市",
    },
    {
        "gov_id": 1801,
        "name": "天心区",
        "children": [],
        "parent_id": 1799,
        "parent_name": "长沙市",
    },
    {
        "gov_id": 1802,
        "name": "岳麓区",
        "children": [],
        "parent_id": 1799,
        "parent_name": "长沙市",
    },
    {
        "gov_id": 1803,
        "name": "开福区",
        "children": [],
        "parent_id": 1799,
        "parent_name": "长沙市",
    },
    {
        "gov_id": 1804,
        "name": "雨花区",
        "children": [],
        "parent_id": 1799,
        "parent_name": "长沙市",
    },
    {
        "gov_id": 1805,
        "name": "望城区",
        "children": [],
        "parent_id": 1799,
        "parent_name": "长沙市",
    },
    {
        "gov_id": 1806,
        "name": "长沙县",
        "children": [],
        "parent_id": 1799,
        "parent_name": "长沙市",
    },
    {
        "gov_id": 1807,
        "name": "宁乡市",
        "children": [],
        "parent_id": 1799,
        "parent_name": "长沙市",
    },
    {
        "gov_id": 1808,
        "name": "浏阳市",
        "children": [],
        "parent_id": 1799,
        "parent_name": "长沙市",
    },
    {
        "gov_id": 1937,
        "name": "荔湾区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1938,
        "name": "越秀区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1939,
        "name": "海珠区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1940,
        "name": "天河区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1941,
        "name": "白云区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1942,
        "name": "黄埔区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1943,
        "name": "番禺区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1944,
        "name": "花都区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1945,
        "name": "南沙区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1946,
        "name": "从化区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 1947,
        "name": "增城区",
        "children": [],
        "parent_id": 1936,
        "parent_name": "广州市",
    },
    {
        "gov_id": 2078,
        "name": "兴宁区",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2079,
        "name": "青秀区",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2080,
        "name": "江南区",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2081,
        "name": "西乡塘区",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2082,
        "name": "良庆区",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2083,
        "name": "邕宁区",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2084,
        "name": "武鸣区",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2085,
        "name": "隆安县",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2086,
        "name": "马山县",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2087,
        "name": "上林县",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2088,
        "name": "宾阳县",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2089,
        "name": "横县",
        "children": [],
        "parent_id": 2077,
        "parent_name": "南宁市",
    },
    {
        "gov_id": 2203,
        "name": "秀英区",
        "children": [],
        "parent_id": 2202,
        "parent_name": "海口市",
    },
    {
        "gov_id": 2204,
        "name": "龙华区",
        "children": [],
        "parent_id": 2202,
        "parent_name": "海口市",
    },
    {
        "gov_id": 2205,
        "name": "琼山区",
        "children": [],
        "parent_id": 2202,
        "parent_name": "海口市",
    },
    {
        "gov_id": 2206,
        "name": "美兰区",
        "children": [],
        "parent_id": 2202,
        "parent_name": "海口市",
    },
    {
        "gov_id": 2230,
        "name": "万州区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2231,
        "name": "涪陵区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2232,
        "name": "渝中区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2233,
        "name": "大渡口区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2234,
        "name": "江北区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2235,
        "name": "沙坪坝区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2236,
        "name": "九龙坡区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2237,
        "name": "南岸区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2238,
        "name": "北碚区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2239,
        "name": "綦江区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2240,
        "name": "大足区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2241,
        "name": "渝北区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2242,
        "name": "巴南区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2243,
        "name": "黔江区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2244,
        "name": "长寿区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2245,
        "name": "江津区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2246,
        "name": "合川区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2247,
        "name": "永川区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2248,
        "name": "南川区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2249,
        "name": "璧山区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2250,
        "name": "铜梁区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2251,
        "name": "潼南区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2252,
        "name": "荣昌区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2253,
        "name": "梁平区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2254,
        "name": "城口县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2255,
        "name": "丰都县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2256,
        "name": "垫江县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2257,
        "name": "武隆区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2258,
        "name": "忠县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2259,
        "name": "开州区",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2260,
        "name": "云阳县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2261,
        "name": "奉节县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2262,
        "name": "巫山县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2263,
        "name": "巫溪县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2264,
        "name": "石柱土家族自治县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2265,
        "name": "秀山土家族苗族自治县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2266,
        "name": "酉阳土家族苗族自治县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2267,
        "name": "彭水苗族土家族自治县",
        "children": [],
        "parent_id": 2229,
        "parent_name": "重庆市",
    },
    {
        "gov_id": 2270,
        "name": "锦江区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2271,
        "name": "青羊区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2272,
        "name": "金牛区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2273,
        "name": "武侯区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2274,
        "name": "成华区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2275,
        "name": "龙泉驿区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2276,
        "name": "青白江区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2277,
        "name": "新都区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2278,
        "name": "温江区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2279,
        "name": "双流区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2280,
        "name": "金堂县",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2281,
        "name": "郫都区",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2282,
        "name": "大邑县",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2283,
        "name": "蒲江县",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2284,
        "name": "新津县",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2285,
        "name": "都江堰市",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2286,
        "name": "彭州市",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2287,
        "name": "邛崃市",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2288,
        "name": "崇州市",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2421,
        "name": "简阳市",
        "children": [],
        "parent_id": 2269,
        "parent_name": "成都市",
    },
    {
        "gov_id": 2475,
        "name": "南明区",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2476,
        "name": "云岩区",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2477,
        "name": "花溪区",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2478,
        "name": "乌当区",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2479,
        "name": "白云区",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2480,
        "name": "观山湖区",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2481,
        "name": "开阳县",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2482,
        "name": "息烽县",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2483,
        "name": "修文县",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2484,
        "name": "清镇市",
        "children": [],
        "parent_id": 2474,
        "parent_name": "贵阳市",
    },
    {
        "gov_id": 2573,
        "name": "五华区",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2574,
        "name": "盘龙区",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2575,
        "name": "官渡区",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2576,
        "name": "西山区",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2577,
        "name": "东川区",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2578,
        "name": "呈贡区",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2579,
        "name": "晋宁区",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2580,
        "name": "富民县",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2581,
        "name": "宜良县",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2582,
        "name": "石林彝族自治县",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2583,
        "name": "嵩明县",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2584,
        "name": "禄劝彝族苗族自治县",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2585,
        "name": "寻甸回族彝族自治县",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2586,
        "name": "安宁市",
        "children": [],
        "parent_id": 2572,
        "parent_name": "昆明市",
    },
    {
        "gov_id": 2719,
        "name": "城关区",
        "children": [],
        "parent_id": 2718,
        "parent_name": "拉萨市",
    },
    {
        "gov_id": 2720,
        "name": "堆龙德庆区",
        "children": [],
        "parent_id": 2718,
        "parent_name": "拉萨市",
    },
    {
        "gov_id": 2721,
        "name": "林周县",
        "children": [],
        "parent_id": 2718,
        "parent_name": "拉萨市",
    },
    {
        "gov_id": 2722,
        "name": "当雄县",
        "children": [],
        "parent_id": 2718,
        "parent_name": "拉萨市",
    },
    {
        "gov_id": 2723,
        "name": "尼木县",
        "children": [],
        "parent_id": 2718,
        "parent_name": "拉萨市",
    },
    {
        "gov_id": 2724,
        "name": "曲水县",
        "children": [],
        "parent_id": 2718,
        "parent_name": "拉萨市",
    },
    {
        "gov_id": 2725,
        "name": "达孜区",
        "children": [],
        "parent_id": 2718,
        "parent_name": "拉萨市",
    },
    {
        "gov_id": 2726,
        "name": "墨竹工卡县",
        "children": [],
        "parent_id": 2718,
        "parent_name": "拉萨市",
    },
    {
        "gov_id": 2801,
        "name": "新城区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2802,
        "name": "碑林区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2803,
        "name": "莲湖区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2804,
        "name": "灞桥区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2805,
        "name": "未央区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2806,
        "name": "雁塔区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2807,
        "name": "阎良区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2808,
        "name": "临潼区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2809,
        "name": "长安区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2810,
        "name": "高陵区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2811,
        "name": "蓝田县",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2812,
        "name": "周至县",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2813,
        "name": "鄠邑区",
        "children": [],
        "parent_id": 2800,
        "parent_name": "西安市",
    },
    {
        "gov_id": 2919,
        "name": "城关区",
        "children": [],
        "parent_id": 2918,
        "parent_name": "兰州市",
    },
    {
        "gov_id": 2920,
        "name": "七里河区",
        "children": [],
        "parent_id": 2918,
        "parent_name": "兰州市",
    },
    {
        "gov_id": 2921,
        "name": "西固区",
        "children": [],
        "parent_id": 2918,
        "parent_name": "兰州市",
    },
    {
        "gov_id": 2922,
        "name": "安宁区",
        "children": [],
        "parent_id": 2918,
        "parent_name": "兰州市",
    },
    {
        "gov_id": 2923,
        "name": "红古区",
        "children": [],
        "parent_id": 2918,
        "parent_name": "兰州市",
    },
    {
        "gov_id": 2924,
        "name": "永登县",
        "children": [],
        "parent_id": 2918,
        "parent_name": "兰州市",
    },
    {
        "gov_id": 2925,
        "name": "皋兰县",
        "children": [],
        "parent_id": 2918,
        "parent_name": "兰州市",
    },
    {
        "gov_id": 2926,
        "name": "榆中县",
        "children": [],
        "parent_id": 2918,
        "parent_name": "兰州市",
    },
    {
        "gov_id": 3020,
        "name": "城东区",
        "children": [],
        "parent_id": 3019,
        "parent_name": "西宁市",
    },
    {
        "gov_id": 3021,
        "name": "城中区",
        "children": [],
        "parent_id": 3019,
        "parent_name": "西宁市",
    },
    {
        "gov_id": 3022,
        "name": "城西区",
        "children": [],
        "parent_id": 3019,
        "parent_name": "西宁市",
    },
    {
        "gov_id": 3023,
        "name": "城北区",
        "children": [],
        "parent_id": 3019,
        "parent_name": "西宁市",
    },
    {
        "gov_id": 3024,
        "name": "大通回族土族自治县",
        "children": [],
        "parent_id": 3019,
        "parent_name": "西宁市",
    },
    {
        "gov_id": 3025,
        "name": "湟中县",
        "children": [],
        "parent_id": 3019,
        "parent_name": "西宁市",
    },
    {
        "gov_id": 3026,
        "name": "湟源县",
        "children": [],
        "parent_id": 3019,
        "parent_name": "西宁市",
    },
    {
        "gov_id": 3072,
        "name": "兴庆区",
        "children": [],
        "parent_id": 3071,
        "parent_name": "银川市",
    },
    {
        "gov_id": 3073,
        "name": "西夏区",
        "children": [],
        "parent_id": 3071,
        "parent_name": "银川市",
    },
    {
        "gov_id": 3074,
        "name": "金凤区",
        "children": [],
        "parent_id": 3071,
        "parent_name": "银川市",
    },
    {
        "gov_id": 3075,
        "name": "永宁县",
        "children": [],
        "parent_id": 3071,
        "parent_name": "银川市",
    },
    {
        "gov_id": 3076,
        "name": "贺兰县",
        "children": [],
        "parent_id": 3071,
        "parent_name": "银川市",
    },
    {
        "gov_id": 3077,
        "name": "灵武市",
        "children": [],
        "parent_id": 3071,
        "parent_name": "银川市",
    },
    {
        "gov_id": 3100,
        "name": "天山区",
        "children": [],
        "parent_id": 3099,
        "parent_name": "乌鲁木齐市",
    },
    {
        "gov_id": 3101,
        "name": "沙依巴克区",
        "children": [],
        "parent_id": 3099,
        "parent_name": "乌鲁木齐市",
    },
    {
        "gov_id": 3102,
        "name": "新市区",
        "children": [],
        "parent_id": 3099,
        "parent_name": "乌鲁木齐市",
    },
    {
        "gov_id": 3103,
        "name": "水磨沟区",
        "children": [],
        "parent_id": 3099,
        "parent_name": "乌鲁木齐市",
    },
    {
        "gov_id": 3104,
        "name": "头屯河区",
        "children": [],
        "parent_id": 3099,
        "parent_name": "乌鲁木齐市",
    },
    {
        "gov_id": 3105,
        "name": "达坂城区",
        "children": [],
        "parent_id": 3099,
        "parent_name": "乌鲁木齐市",
    },
    {
        "gov_id": 3106,
        "name": "米东区",
        "children": [],
        "parent_id": 3099,
        "parent_name": "乌鲁木齐市",
    },
    {
        "gov_id": 3107,
        "name": "乌鲁木齐县",
        "children": [],
        "parent_id": 3099,
        "parent_name": "乌鲁木齐市",
    },
]


_last_character_counts = {
    "区": 269,
    "县": 93,
    "市": 27,
    "旗": 1,
}
