# Generated by Django 4.0.5 on 2022-06-14 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrameFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cached_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_int', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('month_str', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='OneMonthGovsAndIndexes',
            fields=[
                ('dataframefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.dataframefile')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.month')),
            ],
            bases=('base.dataframefile',),
        ),
        migrations.CreateModel(
            name='MultivariateOutliersRemoval',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input', to='base.dataframefile')),
                ('output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output', to='base.dataframefile')),
            ],
            bases=('base.job',),
        ),
    ]
