# Generated by Django 4.0.5 on 2022-06-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrameFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cached_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data_frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input', to='base.dataframefile')),
                ('output_data_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='base.dataframefile')),
            ],
        ),
    ]
