# Generated by Django 4.0.5 on 2022-06-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='input_data_frame',
        ),
        migrations.RemoveField(
            model_name='job',
            name='output_data_frame',
        ),
        migrations.AddField(
            model_name='job',
            name='input_data_frames',
            field=models.ManyToManyField(blank=True, related_name='input', to='base.dataframefile'),
        ),
        migrations.AddField(
            model_name='job',
            name='output_data_frames',
            field=models.ManyToManyField(related_name='output', to='base.dataframefile'),
        ),
    ]
