# Generated by Django 4.0.5 on 2022-06-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataframefile',
            name='history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
