# Generated by Django 4.0.5 on 2022-06-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_job_input_data_frame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_int', models.PositiveSmallIntegerField()),
                ('month_str', models.CharField(max_length=7)),
            ],
        ),
    ]
