# Generated by Django 4.0.5 on 2022-06-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_multivariateoutliersremoval_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='EachColOutliersIdentification',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('deviation_threshold', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_each_col_outliers_identification', to='base.dataframefile')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_each_col_outliers_identification', to='base.dataframefile')),
            ],
            bases=('base.job',),
        ),
    ]
