# Generated by Django 4.0.5 on 2022-06-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_eachcoloutliersidentification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
