# Generated by Django 4.0.5 on 2022-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_job_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframefile',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
