# Generated by Django 4.0.5 on 2022-06-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_job_input_data_frames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multivariateoutliersremoval',
            name='output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output', to='base.dataframefile'),
        ),
    ]
