# Generated by Django 4.0.5 on 2022-06-15 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_dataframefile_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataframefile',
            options={'verbose_name_plural': '1. Data frame files'},
        ),
        migrations.AlterModelOptions(
            name='eachcoloutliersidentification',
            options={'verbose_name_plural': '2.a. Each col outliers identification'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': '2. Jobs'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name_plural': '0.a. Months'},
        ),
        migrations.AlterModelOptions(
            name='onemonthgovsandindexes',
            options={'verbose_name_plural': '1.a. One month govs and indexes'},
        ),
        migrations.CreateModel(
            name='TwoDataFramesComparison',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input1_two_data_frames_comparison', to='base.dataframefile')),
                ('input2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input2_two_data_frames_comparison', to='base.dataframefile')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_two_data_frames_comparison', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.b. Two data frames comparison',
            },
            bases=('base.job',),
        ),
    ]
