# Generated by Django 4.0.5 on 2022-06-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_multivariateoutliersremoval_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='progress',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
