# Generated by Django 4.0.5 on 2022-06-15 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_dataframefile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twodataframescomparison',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_two_data_frames_comparison', to='base.dataframefile'),
        ),
    ]
