# Generated by Django 4.0.5 on 2022-06-15 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_twodataframescomparison_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneMonthGovLevelAndIndexes',
            fields=[
                ('onemonthgovsandindexes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.onemonthgovsandindexes')),
                ('gov_level', models.SmallIntegerField(choices=[(-1, 'GovLevel.ALL'), (0, 'GovLevel.NATION'), (1, 'GovLevel.PROVINCE'), (2, 'GovLevel.CITY_LEVEL'), (3, 'GovLevel.DISTRICT_LEVEL')])),
            ],
            options={
                'verbose_name_plural': '1.b. One month gov level and indexes',
            },
            bases=('base.onemonthgovsandindexes',),
        ),
    ]
