# Generated by Django 4.0.5 on 2022-06-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_onemonthgovlevelandindexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovLevelFiltering',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_gov_level_filtering', to='base.onemonthgovsandindexes')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_gov_level_filtering', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.c. Gov level filtering',
            },
            bases=('base.job',),
        ),
    ]
