# Generated by Django 4.0.5 on 2022-06-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_govlevelfiltering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govlevelfiltering',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_gov_level_filtering', to='base.onemonthgovlevelandindexes'),
        ),
    ]
