# Generated by Django 4.0.5 on 2022-06-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_govlevelfiltering_gov_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onemonthgovlevelandindexes',
            name='onemonthgovsandindexes_ptr',
        ),
        migrations.DeleteModel(
            name='GovLevelFiltering',
        ),
        migrations.DeleteModel(
            name='OneMonthGovLevelAndIndexes',
        ),
    ]
