# Generated by Django 4.0.5 on 2022-06-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_onemonthgovlevelandindexes_govlevelfiltering'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowQualityColsRemoval',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('min_count', models.PositiveBigIntegerField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_low_quality_cols_removal', to='base.dataframefile')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_low_quality_cols_removal', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.d. Low quality cols removal',
            },
            bases=('base.job',),
        ),
    ]
