# Generated by Django 4.0.5 on 2022-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_lowqualitycolsremoval'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowqualitycolsremoval',
            name='min_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowqualitycolsremoval',
            name='min_count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='lowqualitycolsremoval',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('min_count__isnull', True), ('min_quality__isnull', False)), models.Q(('min_count__isnull', False), ('min_quality__isnull', True)), _connector='OR'), name=''),
        ),
    ]
