# Generated by Django 4.0.5 on 2022-06-15 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_lowqualitycolsremoval_min_quality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationCalculation',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_correlation_calculation', to='base.dataframefile')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_correlation_calculation', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.e. Correlation calculation',
            },
            bases=('base.job',),
        ),
    ]
