# Generated by Django 4.0.5 on 2022-06-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_correlationcalculation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorrelationCalculation',
        ),
    ]
