# Generated by Django 4.0.5 on 2022-06-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_featurespairwise_correlationcalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesPairwiseFlat',
            fields=[
                ('dataframefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '1.d. Features pairwise flat',
            },
            bases=('base.dataframefile',),
        ),
        migrations.CreateModel(
            name='SortValuesInFeaturesPairwise',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_sort_values_in_features_pairwise', to='base.featurespairwise')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_sort_values_in_features_pairwise', to='base.featurespairwiseflat')),
            ],
            options={
                'verbose_name_plural': '2.f. Sort values in features pairwise',
            },
            bases=('base.job',),
        ),
    ]
