# Generated by Django 4.0.5 on 2022-06-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_featurespairwiseflat_sortvaluesinfeaturespairwise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multivariateoutliersremoval',
            name='output',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output', to='base.dataframefile'),
        ),
    ]
