# Generated by Django 4.0.5 on 2022-06-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_multivariateoutliersremoval_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachcoloutliersidentification',
            name='output',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_each_col_outliers_identification', to='base.dataframefile'),
        ),
    ]
