# Generated by Django 4.0.5 on 2022-06-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_correlationcalculation_output_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multivariateoutliersremoval',
            options={'verbose_name_plural': '2.z. Todo: Multivariate outliers removal'},
        ),
        migrations.CreateModel(
            name='DispersionCalculation',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_dispersion_calculation', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_dispersion_calculation', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.g. Dispersion calculation',
            },
            bases=('base.job',),
        ),
    ]
