# Generated by Django 4.0.5 on 2022-06-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_multivariateoutliersremoval_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispersioncalculation',
            name='measure_of_dispersion',
            field=models.CharField(choices=[('SD', 'Standard deviation'), ('IQR', 'Interquartile range'), ('CV', 'Coefficient of variation'), ('QCD', 'Quartile coefficient of dispersion')], default='SD', max_length=3),
            preserve_default=False,
        ),
    ]
