# Generated by Django 4.0.5 on 2022-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_dispersioncalculation_measure_of_dispersion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month_str',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
