# Generated by Django 4.0.5 on 2022-06-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_filtervaluesinfeaturespairwiseflat'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lowqualitycolsremoval',
            name='',
        ),
        migrations.AddField(
            model_name='filtervaluesinfeaturespairwiseflat',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filtervaluesinfeaturespairwiseflat',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='filtervaluesinfeaturespairwiseflat',
            constraint=models.CheckConstraint(check=models.Q(('max_value__isnull', False), ('min_value__isnull', False), _negated=True), name='at least one: min_value and max_value'),
        ),
        migrations.AddConstraint(
            model_name='lowqualitycolsremoval',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('min_count__isnull', True), ('min_quality__isnull', False)), models.Q(('min_count__isnull', False), ('min_quality__isnull', True)), _connector='OR'), name='one and only one: min_count or min_quality'),
        ),
    ]
