# Generated by Django 4.0.5 on 2022-06-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_lowqualitycolsremoval__and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Dummy',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #     ],
        # ),
        migrations.RemoveConstraint(
            model_name='filtervaluesinfeaturespairwiseflat',
            name='at least one: min_value and max_value',
        ),
        migrations.RemoveConstraint(
            model_name='lowqualitycolsremoval',
            name='one and only one: min_count or min_quality',
        ),
        migrations.AddConstraint(
            model_name='filtervaluesinfeaturespairwiseflat',
            constraint=models.CheckConstraint(check=models.Q(('max_value__isnull', True), ('min_value__isnull', True), _negated=True), name=''),
        ),
        migrations.AddConstraint(
            model_name='lowqualitycolsremoval',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('min_count__isnull', True), ('min_quality__isnull', False)), models.Q(('min_count__isnull', False), ('min_quality__isnull', True)), _connector='OR'), name='one and only one - min_count or min_quality'),
        ),
    ]
