# Generated by Django 4.0.5 on 2022-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_pca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='index_cols_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
