# Generated by Django 4.0.5 on 2022-06-21 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_pca_index_cols_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='EachColPerCapita',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_each_col_per_capita', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_each_col_per_capita', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.k. Each col per capita',
            },
            bases=('base.job',),
        ),
    ]
