# Generated by Django 4.0.5 on 2022-06-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_downloadonemonth_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesSimilarities',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input_months', models.ManyToManyField(related_name='input_months_time_series_similarities', to='base.onemonthgovsandindexes')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_time_series_similarities', to='base.featurespairwise')),
            ],
            options={
                'verbose_name_plural': '2.n. Time series similarities',
            },
            bases=('base.job',),
        ),
    ]
