# Generated by Django 4.0.5 on 2022-06-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_timeseriessimilarities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
