# Generated by Django 4.0.5 on 2022-06-23 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_eachcolrelativeordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceBetweenColPairs',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('metric', models.CharField(choices=[('euclidean', 'euclidean'), ('cityblock', 'cityblock')], max_length=255)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_distance_between_col_pairs', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_distance_between_col_pairs', to='base.featurespairwise')),
            ],
            options={
                'verbose_name_plural': '2.p. Distance between col pairs',
            },
            bases=('base.job',),
        ),
    ]
