# Generated by Django 4.0.5 on 2022-06-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_distancebetweencolpairs'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowQualityRowsAndColsRemoval',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('min_quality_for_row', models.FloatField()),
                ('min_quality_for_col', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_low_quality_rows_and_cols_removal', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_low_quality_rows_and_cols_removal', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.q. Low quality rows and cols removal',
            },
            bases=('base.job',),
        ),
    ]
