# Generated by Django 4.0.5 on 2022-06-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_lowqualityrowsandcolsremoval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillNA',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_fill_na', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_fill_na', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.q. Fill NA',
            },
            bases=('base.job',),
        ),
    ]
