# Generated by Django 4.0.5 on 2022-06-24 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_fillna'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcValueOntologies',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_calc_value_ontologies', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.q. Calc value ontologies',
            },
            bases=('base.job',),
        ),
    ]
