# Generated by Django 4.0.5 on 2022-06-24 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_calcvalueontologies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calcvalueontologies',
            options={'verbose_name_plural': '2.s. Calc value ontologies'},
        ),
        migrations.AlterModelOptions(
            name='fillna',
            options={'verbose_name_plural': '2.r. Fill NA'},
        ),
        migrations.AddField(
            model_name='appendinfotofeaturespairwiseflat',
            name='input_value_ontologies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_vo_append_info_to_features_pairwise_flat', to='base.dataframefile'),
        ),
    ]
