# Generated by Django 4.0.5 on 2022-06-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_calcvalueontologies_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendinfotofeaturespairwiseflat',
            name='input_dispersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_dispersion_append_info_to_features_pairwise_flat', to='base.dataframefile'),
        ),
    ]
