# Generated by Django 4.0.5 on 2022-06-24 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_appendinfotofeaturespairwiseflat_input_dispersion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendinfotofeaturespairwiseflat',
            name='input_dispersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inputdispersion_append_info_to_features_pairwise_flat', to='base.dataframefile'),
        ),
        migrations.AlterField(
            model_name='appendinfotofeaturespairwiseflat',
            name='input_value_ontologies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inputvo_append_info_to_features_pairwise_flat', to='base.dataframefile'),
        ),
    ]
