# Generated by Django 4.0.5 on 2022-06-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_appendinfotofeaturespairwiseflat_input_dispersion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriessimilarities',
            name='input_months',
            field=models.ManyToManyField(related_name='inputmonths_time_series_similarities', to='base.onemonthgovsandindexes'),
        ),
    ]
