# Generated by Django 4.0.5 on 2022-06-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_timeseriessimilarities_input_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendinfotofeaturespairwiseflat',
            name='input_dispersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_dispersion_append_info_to_features_pairwise_flat', to='base.dataframefile'),
        ),
        migrations.AlterField(
            model_name='appendinfotofeaturespairwiseflat',
            name='input_value_ontologies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_value_ontologies_append_info_to_features_pairwise_flat', to='base.dataframefile'),
        ),
        migrations.AlterField(
            model_name='timeseriessimilarities',
            name='input_months',
            field=models.ManyToManyField(related_name='input_months_time_series_similarities', to='base.onemonthgovsandindexes'),
        ),
    ]
