# Generated by Django 4.0.5 on 2022-06-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_appendinfotofeaturespairwiseflat_input_dispersion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtervaluesinfeaturespairwiseflat',
            name='func_before_filter',
            field=models.CharField(choices=[('ID', 'Identity'), ('ABS', 'Absolute value')], default='ID', max_length=3),
        ),
    ]
