# Generated by Django 4.0.5 on 2022-06-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_filtervaluesinfeaturespairwiseflat_func_before_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='eachcolrelativeordering',
            name='method_of_relative_ordering',
            field=models.CharField(choices=[('PER', 'Percentage'), ('ORD', 'Ordinal')], default='PER', max_length=3),
            preserve_default=False,
        ),
    ]
