# Generated by Django 4.0.5 on 2022-06-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_eachcolrelativeordering_method_of_relative_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachcolrelativeordering',
            name='method_of_relative_ordering',
            field=models.CharField(choices=[('ORD', 'Ordinal'), ('PER', 'Percentage')], default='ORD', max_length=3),
        ),
    ]
