# Generated by Django 4.0.5 on 2022-06-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_eachcolrelativeordering_method_of_relative_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationcalculation',
            name='method',
            field=models.CharField(choices=[('pearson', 'pearson'), ('kendall', 'kendall'), ('spearman', 'spearman')], default='pearson', max_length=15),
        ),
    ]
