# Generated by Django 4.0.5 on 2022-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_filterbyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterbyinfo',
            name='no_same_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filterbyinfo',
            name='no_year_period',
            field=models.BooleanField(default=False),
        ),
    ]
