# Generated by Django 4.0.5 on 2022-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_filterbyinfo_no_same_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterbyinfo',
            name='min_dispersion',
            field=models.FloatField(default=0),
        ),
    ]
