# Generated by Django 4.0.5 on 2022-06-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_filterbyinfo_min_dispersion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterbyinfo',
            name='min_dispersion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pca',
            name='index_cols_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
