# Generated by Django 4.0.5 on 2022-06-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_filterbyinfo_min_dispersion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterbyinfo',
            name='min_dispersion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
