# Generated by Django 4.0.5 on 2022-06-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_filterbyinfo_min_dispersion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcatDataFrames',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input1_concat_data_frames', to='base.dataframefile')),
                ('input2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input2_concat_data_frames', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_concat_data_frames', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.v. Concat data frames',
            },
            bases=('base.job',),
        ),
    ]
