# Generated by Django 4.0.5 on 2022-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_concatdataframes'),
    ]

    operations = [
        migrations.AddField(
            model_name='concatdataframes',
            name='comment',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
