# Generated by Django 4.0.5 on 2022-07-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_downloadonegovmacrodataacrosstime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppendMacroDataInfoToFeaturesPairwiseFlat',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_append_macro_data_info_to_features_pairwise_flat', to='base.featurespairwiseflat')),
                ('input_dispersion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_dispersion_append_macro_data_info_to_features_pairwise_flat', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_append_macro_data_info_to_features_pairwise_flat', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.x. Append macro data info to features pairwise flat',
            },
            bases=('base.job',),
        ),
    ]
