# Generated by Django 4.0.5 on 2022-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_appendmacrodatainfotofeaturespairwiseflat'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendmacrodatainfotofeaturespairwiseflat',
            name='has_input_comments',
            field=models.BooleanField(default=False),
        ),
    ]
