# Generated by Django 4.0.5 on 2022-07-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_discretizeeachcol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRules',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_association_rules', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_association_rules', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.aa. Association Rules',
            },
            bases=('base.job',),
        ),
    ]
