# Generated by Django 4.0.5 on 2022-07-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_associationrules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationrules',
            options={'verbose_name_plural': '2.A. Association Rules'},
        ),
    ]
