# Generated by Django 4.0.5 on 2022-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_alter_associationrules_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discretizeeachcol',
            name='number_of_bins',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
