# Generated by Django 4.0.5 on 2022-07-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_discretizeeachcol_number_of_bins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discretizeeachcol',
            name='number_of_bins',
            field=models.PositiveSmallIntegerField(blank=True, default=3),
        ),
    ]
