# Generated by Django 4.0.5 on 2022-07-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_alter_discretizeeachcol_number_of_bins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframefile',
            name='cached_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
