# Generated by Django 4.0.5 on 2022-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_alter_dataframefile_cached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframefile',
            name='cached_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
