# Generated by Django 4.0.5 on 2022-07-06 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_dataframefile_cached_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationrules',
            options={'verbose_name_plural': '2.A. Association rules'},
        ),
        migrations.CreateModel(
            name='DynamicTimeWarping',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_dynamic_time_warping', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_dynamic_time_warping', to='base.featurespairwise')),
            ],
            options={
                'verbose_name_plural': '2.B. Dynamic time warping',
            },
            bases=('base.job',),
        ),
    ]
