# Generated by Django 4.0.5 on 2022-07-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_normalizeeachcol'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendinfotofeaturespairwiseflat',
            name='has_input_comments',
            field=models.BooleanField(default=False),
        ),
    ]
