# Generated by Django 4.0.5 on 2022-07-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_discretizeandtoonehot'),
    ]

    operations = [
        migrations.AddField(
            model_name='discretizeandtoonehot',
            name='number_of_bins',
            field=models.PositiveSmallIntegerField(blank=True, default=3),
        ),
    ]
