# Generated by Django 4.0.5 on 2022-07-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_discretizeandtoonehot_number_of_bins'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveDispersionSmallCol',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('measure_of_dispersion', models.CharField(choices=[('SD', 'Standard deviation'), ('IQR', 'Interquartile range'), ('CV', 'Coefficient of variation'), ('QCD', 'Quartile coefficient of dispersion')], max_length=3)),
                ('min_dispersion', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_remove_dispersion_small_col', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_remove_dispersion_small_col', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.E. Remove dispersion small col',
            },
            bases=('base.job',),
        ),
    ]
