# Generated by Django 4.0.5 on 2022-07-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_removedispersionsmallcol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispersioncalculation',
            name='measure_of_dispersion',
            field=models.CharField(choices=[('SD', 'Standard deviation'), ('IQR', 'Interquartile range'), ('CV', 'Coefficient of variation'), ('CV2', 'Absolute value of CV (ddof=1)'), ('QCD', 'Quartile coefficient of dispersion')], max_length=3),
        ),
        migrations.AlterField(
            model_name='removedispersionsmallcol',
            name='measure_of_dispersion',
            field=models.CharField(choices=[('SD', 'Standard deviation'), ('IQR', 'Interquartile range'), ('CV', 'Coefficient of variation'), ('CV2', 'Absolute value of CV (ddof=1)'), ('QCD', 'Quartile coefficient of dispersion')], max_length=3),
        ),
    ]
