# Generated by Django 4.0.5 on 2022-07-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_removetoomanyduplicatescol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='removetoomanyduplicatescol',
            options={'verbose_name_plural': '2.F. Remove too many duplicates col'},
        ),
        migrations.CreateModel(
            name='AppendInfoToAssociationRules',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_append_into_association_rules', to='base.featurespairwiseflat')),
                ('input_dispersion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_dispersion_append_info_to_association_rules', to='base.dataframefile')),
                ('input_value_ontologies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_value_ontologies_append_info_to_association_rules', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_append_into_association_rules', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.Z. Append info to association rules',
            },
            bases=('base.job',),
        ),
    ]
