# Generated by Django 4.0.5 on 2022-07-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_alter_removetoomanyduplicatescol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendinfotoassociationrules',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_append_into_association_rules', to='base.dataframefile'),
        ),
    ]
