# Generated by Django 4.0.5 on 2022-07-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_alter_appendinfotoassociationrules_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendinfotoassociationrules',
            name='number_of_bins',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
