# Generated by Django 4.0.5 on 2022-07-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_appendinfotoassociationrules_number_of_bins'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationrules',
            name='max_len',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associationrules',
            name='min_support',
            field=models.FloatField(default=0.3),
            preserve_default=False,
        ),
    ]
