# Generated by Django 4.0.5 on 2022-07-08 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_associationrules_max_len_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentItemSets',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('max_len', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_support', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_frequent_item_sets', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_frequent_item_sets', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.G. Frequent item sets',
            },
            bases=('base.job',),
        ),
    ]
