# Generated by Django 4.0.5 on 2022-07-08 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_frequentitemsets'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveIndexesThatHaveSomeStringInNames',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('some_string', models.TextField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_remove_indexes_that_have_some_string_in_names', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_remove_indexes_that_have_some_string_in_names', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.H. Remove indexes that have some string in names',
            },
            bases=('base.job',),
        ),
    ]
