# Generated by Django 4.0.5 on 2022-07-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_removeindexesthathavesomestringinnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeans',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('n_clusters', models.PositiveSmallIntegerField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_k_means', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_k_means', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.I. K-means',
            },
            bases=('base.job',),
        ),
    ]
