# Generated by Django 4.0.5 on 2022-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_kmeans'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmeans',
            name='use_cols',
            field=models.TextField(blank=True),
        ),
    ]
