# Generated by Django 4.0.5 on 2022-07-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_filterbyvalueinonecol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govlevelfiltering',
            name='gov_level',
            field=models.SmallIntegerField(choices=[(-1, 'ALL'), (0, 'NATION'), (1, 'PROVINCE'), (2, 'CITY_LEVEL'), (3, 'DISTRICT_LEVEL')]),
        ),
        migrations.AlterField(
            model_name='onemonthgovlevelandindexes',
            name='gov_level',
            field=models.SmallIntegerField(choices=[(-1, 'ALL'), (0, 'NATION'), (1, 'PROVINCE'), (2, 'CITY_LEVEL'), (3, 'DISTRICT_LEVEL')]),
        ),
        migrations.CreateModel(
            name='DistrictsPopulationLevelFiltering',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('pop_level', models.SmallIntegerField(choices=[(1, 'LOW'), (2, 'MID_LOW'), (3, 'MID_HIGH'), (4, 'HIGH')])),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_districts_population_level_filtering', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_districts_population_level_filtering', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.K. Districts population level filtering',
            },
            bases=('base.job',),
        ),
    ]
