# Generated by Django 4.0.5 on 2022-07-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_districtsincomelevelfiltering'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictsSevenAreasLevelFiltering',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('seven_areas_level', models.SmallIntegerField(choices=[(0, '华北地区'), (1, '东北地区'), (2, '华东地区'), (3, '华中地区'), (4, '华南地区'), (5, '西南地区'), (6, '西北地区')])),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_districts_seven_areas_level_filtering', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_districts_seven_areas_level_filtering', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.M. Districts seven areas level filtering',
            },
            bases=('base.job',),
        ),
    ]
