# Generated by Django 4.0.5 on 2022-07-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_districtssevenareaslevelfiltering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvincialCapitalsChildrenFiltering',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.job')),
                ('provincial_capitals_children', models.BooleanField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_providential_capitals_children_filtering', to='base.dataframefile')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_providential_capitals_children_filtering', to='base.dataframefile')),
            ],
            options={
                'verbose_name_plural': '2.N. Provincial capitals children filtering',
            },
            bases=('base.job',),
        ),
    ]
